import { Command } from "commander";
import fs from "node:fs";
import path from "node:path";
import fse from "fs-extra";

export function cmdExport() {
  return new Command("export")
    .argument("<workflow_name>")
    .requiredOption("--target <skill>")
    .description("Export workflow as a 'skill' bundle (template)")
    .action((workflowName: string, opts: { target: string }) => {
      if (opts.target !== "skill") throw new Error("only --target skill supported");
      const outDir = path.resolve(process.cwd(), `${workflowName}.skill`);
      fse.removeSync(outDir);
      fse.mkdirpSync(outDir);
      fs.writeFileSync(
        path.join(outDir, "README.md"),
        `# ${workflowName} skill\n\nGenerated by lobster-cli.\n`
      );
      fs.writeFileSync(
        path.join(outDir, "skill.json"),
        JSON.stringify(
          {
            name: workflowName,
            entry: "graph.ts",
            description: "Exported LangGraph workflow",
            runtime: { language: "ts" }
          },
          null,
          2
        )
      );
      process.stdout.write(`OK: exported -> ${path.relative(process.cwd(), outDir)}\n`);
    });
}
